### ISSUE TITLE
Missing autoinclude.zcml

### ISSUE THREAD

**Issue by skillfully** [collective/mr.migrator#13]
Since version/tag 1.1 the autoinclude.zcml called from mr/migrator/runner/**init**.py:71 is missing.

**Comment by macagua** [comment]
@aclark4life @djay I have the same problem report by @skillfully when execute the following command:

```sh
$ ./bin/migrate --help
Traceback (most recent call last):
  File "./bin/migrate", line 113, in <module>
    sys.exit(mr.migrator.runner.runner({},"pipeline.cfg"))
  File "/home/macagua/.buildout/eggs/mr.migrator-1.1-py2.7.egg/mr/migrator/runner/__init__.py", line 71, in runner
    load_config('autoinclude.zcml', mr.migrator)
  File "/home/macagua/.buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/App/zcml.py", line 55, in load_config
    _context = xmlconfig.file(config, package, _context, execute=execute)
  File "/home/macagua/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/home/macagua/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 541, in include
    f = openInOrPlain(path)
  File "/home/macagua/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 429, in openInOrPlain
    fp = open(filename)
IOError: [Errno 2] No such file or directory: '/home/macagua/.buildout/eggs/mr.migrator-1.1-py2.7.egg/mr/migrator/autoinclude.zcml
```

My buildout configuration is the following:

```cfg
[buildout]
auto-checkout = plone.app.blob
extends = https://raw.github.com/collective/buildout.plonetest/master/test-4.3.x.cfg
develop =

parts -= test
parts += migrate

[sources]
plone.app.blob = git git@github.com:aclark4life/plone.app.blob.git

[migrate]
recipe = mr.migrator
pipeline = pipeline.cfg
eggs =
    mr.migrator
    transmogrify.filesystem
    transmogrify.ploneremote
```

Any idea?

**Comment by rpatterson** [comment]
Sounds like whoever built that release didn't have https://pypi.python.org/pypi/setuptools-git installed.

**Comment by macagua** [comment]
@aclark4life @djay If @rpatterson if I defined a specific version like this:
```cfg
[versions]
mr.migrator = 1.0
```

Re-buildout and re-execute the previous command:

```sh
$ ./bin/migrate --help
Usage: migrate [options]

Options:
  -h, --help       show this help message and exit
  --pipeline=FILE  Transmogrifier pipeline.cfg to use
  --show-pipeline  Show contents of the pipeline
  --zcml=ZCML      Load zcml

  source:

  constructor:

  schemaupdater:

  objectpublisher:

  workflowupdater:

  logger:
```

Then I run my Zope instance with ``./bin/instance fg`` and run the command ``./bin/migrate`` and show the following error message:

```sh
$ ./bin/migrate 
Traceback (most recent call last):
  File "./bin/migrate", line 113, in <module>
    sys.exit(mr.migrator.runner.runner({},"pipeline.cfg"))
  File "/home/macagua/.buildout/eggs/mr.migrator-1.0-py2.7.egg/mr/migrator/runner/__init__.py", line 132, in runner
    transmogrifier(pipelineid, **overrides)
  File "/home/macagua/.buildout/eggs/collective.transmogrifier-1.5.1-py2.7.egg/collective/transmogrifier/transmogrifier.py", line 63, in __call__
    for item in pipeline:
  File "/home/macagua/.buildout/eggs/collective.transmogrifier-1.5.1-py2.7.egg/collective/transmogrifier/sections/logger.py", line 39, in __iter__
    for item in self.previous:
  File "/home/macagua/.buildout/eggs/transmogrify.ploneremote-1.3-py2.7.egg/transmogrify/ploneremote/remoteworkflowupdater.py", line 41, in __iter__
    for item in self.previous:
  File "/home/macagua/.buildout/eggs/collective.transmogrifier-1.5.1-py2.7.egg/collective/transmogrifier/sections/inserter.py", line 19, in __iter__
    for item in self.previous:
  File "/home/macagua/.buildout/eggs/transmogrify.ploneremote-1.3-py2.7.egg/transmogrify/ploneremote/remoteschemaupdater.py", line 42, in __iter__
    for item in self.previous:
  File "/home/macagua/.buildout/eggs/transmogrify.ploneremote-1.3-py2.7.egg/transmogrify/ploneremote/remoteconstructor.py", line 45, in __iter__
    self.basepath = proxy.getPhysicalPath()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault -1: 'Unexpected Zope exception: \nTraceback (most recent call last):\n  File "/home/macagua/.buildout/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/Publish.py", line 249, in publish_module_standard\n    response = publish(request, module_name, after_list, debug=debug)\n  File "/home/macagua/.buildout/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/Publish.py", line 177, in publish\n    sys.exc_info()[2],\n  File "/home/macagua/.buildout/eggs/plone.app.linkintegrity-1.5.8-py2.7.egg/plone/app/linkintegrity/monkey.py", line 21, in zpublisher_exception_hook_wrapper\n    return zpublisher_exception_hook(published, REQUEST, t, v, traceback)\n  File "/home/macagua/.buildout/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/Publish.py", line 127, in publish\n    object=request.traverse(path, validated_hook=validated_hook)\n  File "/home/macagua/.buildout/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/BaseRequest.py", line 528, in traverse\n    return response.debugError(e.args)\n  File "/home/macagua/.buildout/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/HTTPResponse.py", line 727, in debugError\n    "\\n%s</p>" % entry)\nNotFound:    Site Error \n   An error was encountered while publishing this resource.\n   \n    Debugging Notice  \n\n  Zope has encountered a problem publishing your object. \nThe object at http://localhost:8080/Plone/getPhysicalPath has an empty or missing docstring. Objects must have a docstring to be published. \n   \n\n   Troubleshooting Suggestions \n\n   \n   The URL may be incorrect. \n   The parameters passed to this resource may be incorrect. \n   A resource that this resource relies on may be\n      encountering an error. \n   \n\n   For more detailed information about the error, please\n  refer to the error log.\n   \n\n   If the error persists please contact the site maintainer.\n  Thank you for your patience.\n   \n'>
```

My pipeline demo is the following:

```cfg
[transmogrifier]
pipeline = 
    source
    constructor
    schemaupdater
    objectpublisher
    workflowupdater
    logger

[constructor]
blueprint = transmogrify.ploneremote.remoteconstructor
target = ${misc:target}

[logger]
blueprint = collective.transmogrifier.sections.logger
level = 1
name = logger
key = _path

[misc]
target = http://admin:admin@localhost:8080/Plone

[objectpublisher]
blueprint = collective.transmogrifier.sections.inserter
key = string:_transitions
value = python:["publish"]

[schemaupdater]
blueprint = transmogrify.ploneremote.remoteschemaupdater
target = ${misc:target}

[source]
blueprint = transmogrify.filesystem
directory = ./data

# We want to create pages not files
file-field = text
file-type = Document

# We do not need to wrap page content in OFS.File
wrap-data = False

[workflowupdater]
blueprint = transmogrify.ploneremote.remoteworkflowupdater
transitions = publish
transitions-key = _transitions
target = ${misc:target}
```

**Comment by macagua** [comment]
@rpatterson then maybe this issue is fixed with a new release?

**Comment by rpatterson** [comment]
@macagua Why?  Do you have some knowledge as to whether the new release was done with `setuptools-git` installed?

**Comment by macagua** [comment]
@rpatterson I believe that Yes!!! I found the bug about "IOError: [Errno 2] No such file or directory", It's coming soon I push the commit with the fix.

**Comment by macagua** [comment]
The problem happens when since version/tag 1.1 try to load the ``autoinclude.zcml`` file called from [mr/migrator/runner/init.py:71](https://github.com/collective/mr.migrator/commit/c1bae8a0b4e8f9c94dcf7d51300dfb3a5a9f7586#diff-ba6e4e9500496762971c1f38486b1491) is missing. The information incluided on  ``autoinclude.zcml`` file was moved into ``configure.zcml`` file at [Line 41](https://github.com/collective/mr.migrator/blob/master/mr/migrator/configure.zcml#L41), as it can see from the commit c4a4837.

**Comment by ramiroluz** [comment]
Any plan on a new release?

The installation of https://pypi.python.org/pypi/funnelweb depends on mr.migrator and the version installed is 1.1

**Comment by djay** [comment]
I just made a 1.2 release. However I don’t think there was any dependency from funnelweb on mr.migrator >= 1.2.

**Comment by ramiroluz** [comment]
Ok, good. I will try it.

Thank you.
