### ISSUE TITLE
Buildout broken >= 4.3

### ISSUE THREAD

**Issue by mamoep** [collective/mr.migrator#15]
Mr.Migrator won't work using buildout. With Plone 4.3 & 5.0 the buildout runs but the client process fails to start with error:

```
2018-03-12 10:38:18 INFO ZEO.ClientStorage zeostorage Disconnected from storage: "('localhost', 9100)"
Traceback (most recent call last):
  File "/data/Plone-4.3/zeocluster/parts/client1/bin/interpreter", line 282, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 131, in startup
    OFS.Application.initialize(application)
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/OFS/Application.py", line 251, in initialize
    initializer.initialize()
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/OFS/Application.py", line 279, in initialize
    self.install_virtual_hosting()
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/OFS/Application.py", line 497, in install_virtual_hosting
    vhm.addToContainer(app)
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Products/SiteAccess/VirtualHostMonster.py", line 113, in addToContainer
    container._setObject(self.id, self)
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/OFS/ObjectManager.py", line 358, in _setObject
    notify(ObjectAddedEvent(ob, self, id))
  File "/data/Plone-4.3/buildout-cache/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/data/Plone-4.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/data/Plone-4.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/data/Plone-4.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/data/Plone-4.3/buildout-cache/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/data/Plone-4.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 32, in objectEventNotify
    zope.component.subscribers((event.object, event), None)
  File "/data/Plone-4.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/data/Plone-4.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/data/Plone-4.3/buildout-cache/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/OFS/subscribers.py", line 110, in dispatchObjectMovedEvent
    callManageAfterAdd(ob, event.object, event.newParent)
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/OFS/subscribers.py", line 143, in callManageAfterAdd
    ob.manage_afterAdd(item, container)
  File "/data/Plone-4.3/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Products/SiteAccess/VirtualHostMonster.py", line 131, in manage_afterAdd
    self.meta_type)
zExceptions.BadRequest: This container already has a Virtual Host Monster
```

With Plone 5.1 the buildout fails completely.
```
Uninstalling precompiler.
Uninstalling zopepy.
Uninstalling client2.
Uninstalling client1.
Updating zeoserver.
Installing client1.
/data/Plone-5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py:208: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Getting distribution for 'mr.migrator'.
Got mr.migrator 1.2.
Getting distribution for 'zope.app.component'.
Got zope.app.component 4.0.0.
Getting distribution for 'configparser'.
Got configparser 3.5.0.
Getting distribution for 'zope.formlib==4.0.6'.
Got zope.formlib 4.0.6.
Getting distribution for 'zope.app.pagetemplate>=4.0'.
Got zope.app.pagetemplate 4.0.0.
Version and requirements information containing zope.app.container:
  [versions] constraint on zope.app.container: 3.9.2
  Requirement of collective.jsonmigrator: zope.app.container
  Requirement of zope.app.component: zope.app.container>=4.0
  Requirement of zope.app.container: zope.traversing
  Requirement of zope.app.container: zope.size
  Requirement of zope.app.container: zope.security
  Requirement of zope.app.container: zope.publisher>=3.12
  Requirement of zope.app.container: zope.location
  Requirement of zope.app.container: zope.lifecycleevent
  Requirement of zope.app.container: zope.interface
  Requirement of zope.app.container: zope.i18nmessageid
  Requirement of zope.app.container: zope.i18n
  Requirement of zope.app.container: zope.exceptions
  Requirement of zope.app.container: zope.event
  Requirement of zope.app.container: zope.dublincore>=3.7
  Requirement of zope.app.container: zope.copypastemove
  Requirement of zope.app.container: zope.container
  Requirement of zope.app.container: zope.component
  Requirement of zope.app.container: zope.browserpage
  Requirement of zope.app.container: zope.browsermenu
  Requirement of zope.app.container: zope.browser
  Requirement of zope.app.container: setuptools
While:
  Installing client1.
Error: The requirement ('zope.app.container>=4.0') is not allowed by your [versions] constraint (3.9.2)

```

**Comment by greskwerk** [comment]
Same here (Products.CMFPlone  = 5.1.2.1)

./bin/buildout install migrator
Getting distribution for 'mr.migrator'.
Got mr.migrator 1.2.
Getting distribution for 'zope.app.component'.
Got zope.app.component 4.0.0.
Getting distribution for 'configparser'.
Got configparser 3.5.0.
Getting distribution for 'zope.formlib==4.0.6'.
Got zope.formlib 4.0.6.
Getting distribution for 'zope.app.pagetemplate>=4.0'.
Got zope.app.pagetemplate 4.0.0.
Version and requirements information containing zope.app.container:
  [versions] constraint on zope.app.container: 3.9.2
  Requirement of zope.app.component: zope.app.container>=4.0
While:
  Installing.
  Loading extensions.
  Getting section migrator.
  Initializing section migrator.
  Installing recipe mr.migrator.
Error: The requirement ('zope.app.container>=4.0') is not allowed by your [versions] constraint (3.9.2)

**Comment by djowett** [comment]
Sounds like a product somewhere is pulling in Zope4. I had that the other day and found in my case it was plone.testing which needed pinning to 5.0.0.  Not saying that it's the same for you, but try running buildout with -vv and get a better idea of what pins are there for zope* packages.

**Comment by canepan** [comment]
Is there any fix for this?
It is happening the same to me, and `buildout -vv` is partially helping: I can see that `zope.app.component` requires `zope.app.container>=4.0`, but I don't know which version will be fine with 3.9.2.
Here is the relevant output:
> Version and requirements information containing zope.app.container:
  [versions] constraint on zope.app.container: 3.9.2
  Requirement of zope.app.component: zope.app.container>=4.0
While:
  Installing instance.
Error: The requirement ('zope.app.container>=4.0') is not allowed by your [versions] constraint (3.9.2)

**Comment by djowett** [comment]
I guess what's happening is that `zope.app.component` is required by this product ([here](https://github.com/collective/mr.migrator/blob/master/setup.py#L25)) and that is unpinned by plone versions or your own buildout.  You (@greskwerk and @canepan) are therefore pulling in parts of zope 4, which you almost certainly don't want.

I'd suggest you add a pin like `zope.app.component < 4.0` to your buildout and consider doing so for any other zope products that get into 4.x terriotry.

I don't know whether zope.app.component is really a requirement here, but if so it probably isn't correct  to pin it in this product as some folk might _want_ to use it in Zope 4

**Comment by canepan** [comment]
After fixing `zope.app.container`, I am facing this:
>   Requirement of five.formlib: zope.formlib>=4.4
  Requirement of five.formlib>=1.0.2: zope.formlib>=4.4
  Requirement of zope.app.form: zope.formlib>=4.0

And unfortunately it looks like it's [here](https://github.com/plone/buildout.coredev/blob/5.1/versions.cfg#L182).
I can downgrade `five.formlib`, but not `zope.app.form`

**Comment by djowett** [comment]
Why are you using the coredev buildout? 

On 19 March 2019 06:20:14 GMT, canepan <notifications@github.com> wrote:
>After fixing `zope.app.container`, I am facing this:
>>   Requirement of five.formlib: zope.formlib>=4.4
>  Requirement of five.formlib>=1.0.2: zope.formlib>=4.4
>  Requirement of zope.app.form: zope.formlib>=4.0
>
>And unfortunately it looks like it's
>[here](https://github.com/plone/buildout.coredev/blob/5.1/versions.cfg#L182).
>I can downgrade `five.formlib`, but not `zope.app.form`
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/collective/mr.migrator/issues/15#issuecomment-474212898

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by canepan** [comment]
I'm using the [docker image](https://github.com/plone/plone.docker), and trying to customize it for my needed packages
